pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-server-ip')
    }
    stages {
        stage('Setup') {
            steps {
                sh """
                    pwd
                    cd 02-single-server-deployment/
                    pip install -r requirements.txt --break-system-packages
                """
            }
        }
        stage('Test') {
            steps {
                echo "Testing Start..."
                sh """
                    cd 02-single-server-deployment/
                    pwd
                    pytest
                """
            }
        }

        stage('Package code') {
            steps {
                sh """
                    echo 'Packaging Code Start...'
                    cd 02-single-server-deployment/
                    pwd
                    zip -r myapp.zip ./* -x '*.git*'
                    ls -lart
                """
            }
        }

        stage('Deploy to Prod') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-key-pair', keyFileVariable: 'MY_SSH_KEY', usernameVariable: 'username')]) {
                    sh '''
                    echo 'Deployment Start Here..!'
                    pwd
                    scp -i $MY_SSH_KEY -o StrictHostKeyChecking=no myapp.zip  ${username}@${SERVER_IP}:/home/ec2-user/
                    ssh -i $MY_SSH_KEY -o StrictHostKeyChecking=no ${username}@${SERVER_IP} << EOF
                        unzip -o /home/ec2-user/myapp.zip -d /home/ec2-user/app/
                        source app/venv/bin/activate
                        cd /home/ec2-user/app/
                        pip install -r requirements.txt
                        sudo systemctl restart flaskapp.service
EOF
                    '''
                }
            }
        }
       
        
       
        
    }
}